[character]
success_symbol = "[â¯](bold green)"
error_symbol =  "[â¯](bold red)"

[directory]
truncation_length = 22
truncate_to_repo = false

[git_branch]
symbol = "ğŸŒ± "

[git_status]
style = "bold yellow"
modified = "!"
