[[battery.display]]
threshold = 25
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)" 
error_symbol = "[âœ—](bold red)"

[directory]
truncation_length = 100 
format = "[$path]($style) "
style = "bold cyan"

[git_branch]
symbol = "ğŸŒ± "
style = "bold green"

[git_commit]
commit_hash_length = 6
style = "bold green"

[git_status]
style = "bold green"

[package]
format = "via [ğŸ‡ $version](166 bold) "
